//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Items
    {
        public int Inventory_ID { get; set; }
        public int Item_ID { get; set; }
        public int Item_Quantity { get; set; }
        public Nullable<int> Transfer_to { get; set; }
        public Nullable<int> Transfer_from { get; set; }
        public Nullable<System.DateTime> Transfer_Date { get; set; }
        public Nullable<int> Quantity_Transferred { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Item Item { get; set; }
    }
}
